baseURL = "https://www.disgone.com/"
languageCode = "en-US"
canonifyurls = true
title = "Shaun Smith"
theme = "hugo-theme-vault"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true
googleAnalytics = "UA-771294-5"

[params]
    description= "Personal website of Shaun Smith, a software developer in the Dallas, Texas area."
    paginate = 15
    latestposts = 5
    error_404 = "Oh man, I can't find what you're looking for."
    tokenSeperator = " | "
    date_format = "January 2, 2006"
    copyright = "2003 - 2018 Shaun Smith"

[social]
    twitter = "disgone"
    github = "disgone"
    facebook = "the.shaun.smith"
    stackoverflow = "253542"
    googleplus = "118435294559780760871"
    email = "shaunsmith@disgone.com"

[permalinks]
    pages = ":filename/"
    blog = "blog/:year/:month/:day/:slug/"

[author]
    name = "Shaun Smith"

[[menu.main]]
    name = "Home"
    url = "/"
    identifier = "home"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    identifier = "about"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    identifier = "blog"
    weight = 3
